<?php
return array (
  2 => 
  array (
    'id' => '2',
    'catid' => '14',
    'typeid' => '0',
    'title' => '莆田市移动公司莅临新泽尔科技参观交流',
    'style' => '',
    'thumb' => 'http://localhost/219/pc/uploadfile/2019/1105/20191105051557134.jpg',
    'keywords' => '莆田市移动公司',
    'description' => '莆田市移动公司莅临新泽尔科技参观交流',
    'posids' => '1',
    'url' => 'http://localhost/219/pc/index.php?m=content&c=index&a=show&catid=14&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1572945129',
    'updatetime' => '1574489946',
    'hitsid' => 'c-1-2',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '2',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '14',
    'typeid' => '0',
    'title' => '日媒：日俄领土谈判中断至今 安倍被迫处于守势|领土谈判',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　原标题：日媒：日俄领土谈判中断至今，安倍被迫处于守势　　[环球网报道 记者 王欢]日本首相安倍晋三当地时间9月10日在俄罗斯符拉迪   ',
    'posids' => '0',
    'url' => 'http://localhost/219/pc/index.php?m=content&c=index&a=show&catid=14&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1572947340',
    'updatetime' => '1574489955',
    'hitsid' => 'c-1-3',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '2',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '14',
    'typeid' => '0',
    'title' => '美突然禁止俄新侦察机按天空条约执飞 未解释缘由|开放天',
    'style' => '',
    'thumb' => 'http://n.sinaimg.cn/translate/741/w1000h541/20180912/T40j-hiycyfx5656833.jpg',
    'keywords' => '',
    'description' => '　　原标题：突然，美国无缘由禁止俄新型侦察机按开放天空条约执行飞行　　[环球网综合报道]俄罗斯减少核危险国家中心主任谢尔盖∙雷日科夫   ',
    'posids' => '0',
    'url' => 'http://localhost/219/pc/index.php?m=content&c=index&a=show&catid=14&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1572947340',
    'updatetime' => '1572948005',
    'hitsid' => 'c-1-5',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '14',
    'typeid' => '0',
    'title' => '安倍与蒙古总统会谈 确认为解决朝鲜绑架问题合作|蒙古|',
    'style' => '',
    'thumb' => 'http://n.sinaimg.cn/translate/714/w960h554/20180912/lVtI-hiycyfx5656531.jpg',
    'keywords' => '',
    'description' => '　　原标题：安倍与蒙古总统会谈，确认为解决朝鲜绑架日本人问题合作　　[环球网报道 记者 王欢]日本首相安倍晋三9月11日下午在俄罗斯符   ',
    'posids' => '0',
    'url' => 'http://localhost/219/pc/index.php?m=content&c=index&a=show&catid=14&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1572947340',
    'updatetime' => '1572947996',
    'hitsid' => 'c-1-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '14',
    'typeid' => '0',
    'title' => '法极右政党党魁：法院若决定冻结补助 该党必死|政党|党',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　原标题：法极右政党党魁：法院若决定冻结补助 该党必死无疑　　[环球网报道 记者 王莉兰]法国《欧洲时报》9月11日报道称，法国极右   ',
    'posids' => '0',
    'url' => 'http://localhost/219/pc/index.php?m=content&c=index&a=show&catid=14&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1572947342',
    'updatetime' => '1572948357',
    'hitsid' => 'c-1-6',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '14',
    'typeid' => '0',
    'title' => '美国务院：蓬佩奥无立即访朝计划 &ldquo;小扁人&rdquo;想去|蓬佩奥',
    'style' => '',
    'thumb' => '//n.sinaimg.cn/translate/118/w1024h694/20180912/3FuR-hiycyfx6377156.jpg',
    'keywords' => '',
    'description' => '　　原标题：美国务院：蓬佩奥没有立即访朝计划，&ldquo;小扁人斯坦利&rdquo;想去美国国务卿蓬佩奥 （图片来源：韩联社）　　[环球网报道 记者 李   ',
    'posids' => '0',
    'url' => 'http://localhost/219/pc/index.php?m=content&c=index&a=show&catid=14&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1572947342',
    'updatetime' => '1572948357',
    'hitsid' => 'c-1-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '14',
    'typeid' => '0',
    'title' => '利比亚首都机场遭炮击 尚无人员伤亡财产损失报告|利比亚',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　原标题：利比亚首都机场遭炮击 尚无人员伤亡和财产损失报告　　中新网9月12日电 据俄罗斯卫星网12日援引外媒报道，利比亚首都的黎波   ',
    'posids' => '0',
    'url' => 'http://localhost/219/pc/index.php?m=content&c=index&a=show&catid=14&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1572947342',
    'updatetime' => '1572948357',
    'hitsid' => 'c-1-8',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '14',
    'typeid' => '0',
    'title' => '法国女子教唆年轻女性加入IS 被判7年监禁|法国|圣战|女',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '　　原标题：法国女子教唆年轻女性加入IS 被判7年监禁　　[环球网报道 记者 王莉兰]据法国《欧洲时报》9月11日援引法新社报道，近日，法   ',
    'posids' => '0',
    'url' => 'http://localhost/219/pc/index.php?m=content&c=index&a=show&catid=14&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1572947342',
    'updatetime' => '1572948357',
    'hitsid' => 'c-1-9',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>