<?php
return array (
  11 => 
  array (
    'id' => '11',
    'catid' => '15',
    'typeid' => '0',
    'title' => '日本河豚&ldquo;杂种化&rdquo;现象激增 导致&ldquo;有毒难辨&rdquo;|河豚|杂',
    'style' => '',
    'thumb' => 'http://n.sinaimg.cn/translate/243/w597h446/20180912/vWGS-fzrwica3248672.jpg',
    'keywords' => '',
    'description' => '　　原标题：要命！日本河豚&ldquo;杂种化&rdquo;现象激增导致&ldquo;有毒难辨&rdquo;　　[环球网报道 记者 王欢]由于气候变暖导致海水温度上升，河豚的栖息地   ',
    'posids' => '0',
    'url' => 'http://localhost/219/pc/index.php?m=content&c=index&a=show&catid=15&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1572947341',
    'updatetime' => '1572948432',
    'hitsid' => 'c-1-11',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  12 => 
  array (
    'id' => '12',
    'catid' => '15',
    'typeid' => '0',
    'title' => '大规模性侵丑闻席卷体坛 美奥委会主席将引咎辞职|性侵丑',
    'style' => '',
    'thumb' => '//n.sinaimg.cn/translate/220/w600h420/20180912/8ovG-fzrwica3249203.jpg',
    'keywords' => '',
    'description' => '　　原标题：大规模性侵丑闻席卷美体坛 美奥委会主席将引咎辞职资料图：美国奥委会主席普罗布斯特（新华社）　　参考消息网9月12日报道    ',
    'posids' => '0',
    'url' => 'http://localhost/219/pc/index.php?m=content&c=index&a=show&catid=15&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1572947341',
    'updatetime' => '1572948432',
    'hitsid' => 'c-1-12',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  13 => 
  array (
    'id' => '13',
    'catid' => '15',
    'typeid' => '0',
    'title' => '联合国粮农组织：2017年约有8.2亿人面临粮食短缺|粮食|短',
    'style' => '',
    'thumb' => 'http://n.sinaimg.cn/translate/183/w628h355/20180912/5vEB-hiycyfx6050137.jpg',
    'keywords' => '',
    'description' => '　　原标题：联合国粮农组织：2017年约有8 2亿人面临粮食短缺问题　　[环球网报道 记者 屈腾飞]日本NHK电视台9月12日报道称，联合国粮农   ',
    'posids' => '0',
    'url' => 'http://localhost/219/pc/index.php?m=content&c=index&a=show&catid=15&id=13',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1572947341',
    'updatetime' => '1572948432',
    'hitsid' => 'c-1-13',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  14 => 
  array (
    'id' => '14',
    'catid' => '15',
    'typeid' => '0',
    'title' => '飓风弗洛伦斯来袭 美国170万居民急撤离公路拥堵|弗洛伦',
    'style' => '',
    'thumb' => 'http://n.sinaimg.cn/translate/154/w552h402/20180912/Pgj3-hiycyfx5939689.png',
    'keywords' => '',
    'description' => '　　原标题：飓风&ldquo;弗洛伦斯&rdquo;即将来袭 美国170万居民急撤离 公路车流拥堵　　当地时间11日，美国国家飓风中心的信息显示，4级飓风&ldquo;弗洛   ',
    'posids' => '0',
    'url' => 'http://localhost/219/pc/index.php?m=content&c=index&a=show&catid=15&id=14',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1572947341',
    'updatetime' => '1572948432',
    'hitsid' => 'c-1-14',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  15 => 
  array (
    'id' => '15',
    'catid' => '15',
    'typeid' => '0',
    'title' => '杜特尔特向士兵喊话：不满意我领导 可发动兵变|杜特尔特',
    'style' => '',
    'thumb' => '//n.sinaimg.cn/news/crawl/116/w550h366/20180912/DvY8-hiixpun6785643.jpg',
    'keywords' => '',
    'description' => '　　原标题：杜特尔特向士兵喊话：不满意我领导 可发动兵变菲律宾总统杜特尔特（图：视觉中国）　　海外网9月12日电 菲律宾总统杜特尔特   ',
    'posids' => '0',
    'url' => 'http://localhost/219/pc/index.php?m=content&c=index&a=show&catid=15&id=15',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1572947341',
    'updatetime' => '1572948432',
    'hitsid' => 'c-1-15',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>